# Generated by Django 6.0.4 on 2026-04-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=10, help_text='Duration in Minutes'),
        ),
        migrations.AddField(
            model_name='quizinvitation',
            name='started_At',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
