# Generated by Django 6.0.4 on 2026-04-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_quiz_duration_quizinvitation_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattempt',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
