# Generated by Django 6.0.4 on 2026-04-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='User Profile', null=True),
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
